### ISSUE TITLE
DropboxClient class retired

### ISSUE THREAD

**Issue by OptimusGREEN** [micahg/script.module.dropbox#5]
Hi,

Any plans to update this from v1 to v2 sdk?

Apparently DropBoxClient no longer works and it has to be dropbox.Dropbox

**Comment by micahg** [comment]
Thanks for the heads up -- I didn't even realise it'd stopped working. I'll look into it when I have time.

**Comment by SchapplM** [comment]
Would it make more sense to create a new kodi addon with the new dropbox API v2?
@OptimusGREEN started a [repo for script.module.dropbox2](https://github.com/OptimusGREEN/script.module.dropbox2/) with the new API with a [pull request to the Kodi addons repo](https://github.com/xbmc/repo-scripts/issues/619).
@micahg refactored his [addon script.module.dropbox](https://github.com/micahg/script.module.dropbox) for the new API.
Since all files in the addon would change **I would favor using a new addon and abandoning the old one**.

Currently my [addon service.watchedlist](https://github.com/SchapplM/xbmc-addon-service-watchedlist) is the only one using the dropbox API addon, but the DBMC addon should also use the dedicated API addon module. I [started working on the Dropbox API v2 interface](https://github.com/SchapplM/xbmc-addon-service-watchedlist/issues/30) but just found out @micahg [did the same](https://github.com/micahg/xbmc-addon-service-watchedlist/tree/dropbox_v2).

What do you think?

**Comment by micahg** [comment]
I think, wrt to getting it into the main repo, we are probably better off bumping the version. This is how the requests module works too. Speaking of which, we can't go forward until this:

https://github.com/beenje/script.module.requests/issues/16

resolves this:

https://github.com/dropbox/dropbox-sdk-python/issues/106

But, while that is getting fixed, I do plan on getting a version of watchedlist working with the new api. I'll have a patch ready to go in as soon as requests is fixed.

**Comment by micahg** [comment]
Hello all,

I just pushed up https://github.com/xbmc/repo-scripts/pull/664 so hopefully it gets fixed soon.  @SchapplM, I have a branch of wathedlist in my repo working with the new API at https://github.com/micahg/xbmc-addon-service-watchedlist/commits/dropbox_v2.

Right now it still needs a bit of cleanup but I'll get a PR out soon.

Also, important to note, the dropbox api depends on script.module.requests 2.18 or above, which depends on python 2.25.0. This breaks backwards compatibility with pre-krypton releases.

**Comment by robweber** [comment]
Saw the pull request for this in the repo. As luck would have it I just committed a whole bunch of code to get the dropbox v2 system working with the Backup addon as well. We more than likely were doing this at the exact same time - which to me seems like a giant waste of time. As I saw in your commits as well there are a lot of small tweaks that had to be made to the dropbox api to get it working with Kodi. In the future it might save us both a lot of time to "borrow" fixes from each other in regards to that library. Here is a link to my branch with the updates: https://github.com/robweber/xbmcbackup/tree/dropbox_v2 

One big difference I noticed is that I was able to get it working withe the requests module 2.12.4 while you said it needs 2.18. Not sure the difference there but I tested authorization, file downloads, directory listing, file uploads, and meta data checks. All worked. You can keep backward compatibility with pre-Krypton releases with that version.

**Comment by SchapplM** [comment]
@robweber, would it make sense to use the script.module.dropbox for the Backup addon as well as for the WatchedList addon (and other addons)? Keeping it modular could prevent double work in future.

**Comment by micahg** [comment]
I agree. I mean, I don't want to tell you what to do with your addon, but if we can all share a common code base we'd all be better off.

I'm also happy to make changes to make it more compatible (eg: not needing pythong 2.25/requests 2.18.4) but I would like to keep it in the module repo so everyone can use it.

I've been super busy, but I'm hoping to cleanup the PR and get it merged soon.

**Comment by robweber** [comment]
@SchapplM  - I agree. I was unfamiliar with this addon until I saw the PR. At first I thought it was a replacement to the old Dropbox addon that was more of a dropbox client for Kodi. I see this one is just the Dropbox python library packaged for other addons to use - very useful. Like a lot of libraries some tweaking is always needed to get it working with Kodi and keeping it modular is a big help. 

I'm going to refactor the Backup addon to use this as a dependency instead of trying to keep that code internal to the addon. Appreciate the work you've put into this.
